//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserStorageMonitor.UserStorageServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmptyQuery", Namespace="http://schemas.datacontract.org/2004/07/UserStorage.Diagnostics.Query")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserStorageMonitor.UserStorageServiceReference.SelectAllServicesQuery))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserStorageMonitor.UserStorageServiceReference.SelectServicesWithSpecifiedNameQuery))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserStorageMonitor.UserStorageServiceReference.SelectServicesWithNameContainsQuery))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserStorageMonitor.UserStorageServiceReference.SelectServicesWithSpecifiedTypeQuery))]
    public partial class EmptyQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectAllServicesQuery", Namespace="http://schemas.datacontract.org/2004/07/UserStorage.Diagnostics.Query")]
    [System.SerializableAttribute()]
    public partial class SelectAllServicesQuery : UserStorageMonitor.UserStorageServiceReference.EmptyQuery {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectServicesWithSpecifiedNameQuery", Namespace="http://schemas.datacontract.org/2004/07/UserStorage.Diagnostics.Query")]
    [System.SerializableAttribute()]
    public partial class SelectServicesWithSpecifiedNameQuery : UserStorageMonitor.UserStorageServiceReference.EmptyQuery {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectServicesWithNameContainsQuery", Namespace="http://schemas.datacontract.org/2004/07/UserStorage.Diagnostics.Query")]
    [System.SerializableAttribute()]
    public partial class SelectServicesWithNameContainsQuery : UserStorageMonitor.UserStorageServiceReference.EmptyQuery {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameText {
            get {
                return this.NameTextField;
            }
            set {
                if ((object.ReferenceEquals(this.NameTextField, value) != true)) {
                    this.NameTextField = value;
                    this.RaisePropertyChanged("NameText");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectServicesWithSpecifiedTypeQuery", Namespace="http://schemas.datacontract.org/2004/07/UserStorage.Diagnostics.Query")]
    [System.SerializableAttribute()]
    public partial class SelectServicesWithSpecifiedTypeQuery : UserStorageMonitor.UserStorageServiceReference.EmptyQuery {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceInfo", Namespace="http://schemas.datacontract.org/2004/07/UserStorage.Diagnostics")]
    [System.SerializableAttribute()]
    public partial class ServiceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceDebugInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceDebugInfo {
            get {
                return this.ServiceDebugInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceDebugInfoField, value) != true)) {
                    this.ServiceDebugInfoField = value;
                    this.RaisePropertyChanged("ServiceDebugInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceType {
            get {
                return this.ServiceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceTypeField, value) != true)) {
                    this.ServiceTypeField = value;
                    this.RaisePropertyChanged("ServiceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceUrl {
            get {
                return this.ServiceUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceUrlField, value) != true)) {
                    this.ServiceUrlField = value;
                    this.RaisePropertyChanged("ServiceUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserStorageServiceReference.Monitor")]
    public interface Monitor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Monitor/GetServicesCount", ReplyAction="http://tempuri.org/Monitor/GetServicesCountResponse")]
        int GetServicesCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Monitor/GetServicesCount", ReplyAction="http://tempuri.org/Monitor/GetServicesCountResponse")]
        System.Threading.Tasks.Task<int> GetServicesCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Monitor/QueryServices", ReplyAction="http://tempuri.org/Monitor/QueryServicesResponse")]
        UserStorageMonitor.UserStorageServiceReference.ServiceInfo[] QueryServices(UserStorageMonitor.UserStorageServiceReference.EmptyQuery queryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Monitor/QueryServices", ReplyAction="http://tempuri.org/Monitor/QueryServicesResponse")]
        System.Threading.Tasks.Task<UserStorageMonitor.UserStorageServiceReference.ServiceInfo[]> QueryServicesAsync(UserStorageMonitor.UserStorageServiceReference.EmptyQuery queryType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MonitorChannel : UserStorageMonitor.UserStorageServiceReference.Monitor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorClient : System.ServiceModel.ClientBase<UserStorageMonitor.UserStorageServiceReference.Monitor>, UserStorageMonitor.UserStorageServiceReference.Monitor {
        
        public MonitorClient() {
        }
        
        public MonitorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetServicesCount() {
            return base.Channel.GetServicesCount();
        }
        
        public System.Threading.Tasks.Task<int> GetServicesCountAsync() {
            return base.Channel.GetServicesCountAsync();
        }
        
        public UserStorageMonitor.UserStorageServiceReference.ServiceInfo[] QueryServices(UserStorageMonitor.UserStorageServiceReference.EmptyQuery queryType) {
            return base.Channel.QueryServices(queryType);
        }
        
        public System.Threading.Tasks.Task<UserStorageMonitor.UserStorageServiceReference.ServiceInfo[]> QueryServicesAsync(UserStorageMonitor.UserStorageServiceReference.EmptyQuery queryType) {
            return base.Channel.QueryServicesAsync(queryType);
        }
    }
}
